[build]
  publish = "build"
  command = "yarn run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://www.contentfulapp.com/api"
  status = 200
  force = true