[build]
  publish = "build"
  command = "yarn run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://contentful-api.netlify.com/:splat"
  status  = 200