[build]
  publish = "build"
  command = "yarn run build"

[[redirects]]
  from = "/api/*"
  to = "https://contentful-api.netlify.com/.netlify/functions/server/:splat"
  status  = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false