[build]
  publish = "build"
  command = "yarn run build"

[[redirects]]
  from = "/api"
  to = "https://contentful-api.netlify.com/.netlify/functions/server"
  status  = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200